apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hzj-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - next.hezongjian.com
    secretName: hzj-tls
  rules:
  - host: next.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: hzj-svc
          servicePort: 80
