apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: blog
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: hzj-svc
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer: {}

