name: KUBE

on:
  # Trigger the workflow on push only for the master branch
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v1
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Checkout themes and plugins
      run: |
        git clone https://github.com/getpelican/pelican-themes.git ../pelican-themes
        git clone https://github.com/getpelican/pelican-plugins.git ../pelican-plugins
    
    - name: Generate HTML
      run: |
        make clean
        make publish
    
    - name: build docker
      run: |
          docker build . -t hezongjian/blog:${{ github.sha }} -t hezongjian/blog:latest
    
    - name: Publish to Docker Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: hezongjian/blog
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        tags: "latest, ${{ github.sha }}"
    
    - name: deploy to cluster
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: set image --record deployment/hzj-deployment hzj-nginx=hezongjian/blog:${{ github.sha }}
    
    - name: verify deployment
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "1.15"
      with:
        args: rollout status deployment/hzj-deployment
